#!/bin/bash
#
# Open a tunnel with a server through Azure Bastion

# LIST OF AZURE TENANTS
IIIM_tenant="iiimprod.onmicrosoft.com"
IIIM_config_dir="$HOME/.azure_IIIM"
IIMM_tenant="mymeprod.onmicrosoft.com"
IIMM_config_dir="$HOME/.azure_IIMM"
UNDP_tenant="iccundp.onmicrosoft.com"
UNDP_config_dir="$HOME/.azure_UNDP"
UNWOMEN_tenant="unwomen.onmicrosoft.com"
UNWOMEN_config_dir="$HOME/.azure_WOMEN"

export AZURE_CONFIG_DIR=$IIIM_config_dir
if az account show &>/dev/null
then
   iiim="\Zu\Z1IIIM"
else
   iiim="IIIM"
fi

export AZURE_CONFIG_DIR=$IIMM_config_dir
if az account show &>/dev/null
then
   iimm="\Zu\Z1IIMM"
else
   iimm="IIMM"
fi

export AZURE_CONFIG_DIR=$UNDP_config_dir
if az account show &>/dev/null
then
   undp="\Zu\Z1UNDP"
else
   undp="UNDP"
fi

export AZURE_CONFIG_DIR=$UNWOMEN_config_dir
if az account show &>/dev/null
then
   unwomen="\Zu\Z1UNWOMEN"
else
   unwomen="UNWOMEN"
fi

tenant="$(dialog --colors --backtitle "Azure Bastion tunnel connection" --title "\Zb\Z0AZBASTION" --stdout --default-item 1 --menu "Select Tenant" 0 0 6 \
  1 "$iiim" \
  2 "$iimm" \
  3 "$undp" \
  4 "$unwomen")"

case $tenant in
  1)
    export AZURE_CONFIG_DIR=$IIIM_config_dir
    if ! az account show &>/dev/null
    then
      az login --tenant $IIIM_tenant &>> /tmp/azbastion_$USER.log
      az account set --subscription 'IIIM - Connectivity Hub'
    fi;;
  2)
    export AZURE_CONFIG_DIR=$IIMM_config_dir
    if ! az account show &>/dev/null
    then
      az login --tenant $IIMM_tenant &>> /tmp/azbastion_$USER.log
      az account set --subscription 'IIMM - Connectivity Hub' 
    fi;;
  3)
    export AZURE_CONFIG_DIR=$UNDP_config_dir
    if ! az account show &>/dev/null
    then
      az login --tenant $UNDP_tenant &>> /tmp/azbastion_$USER.log
      az account set --subscription 'ICCUNDP - Production'
    fi;;
  4) 
    export AZURE_CONFIG_DIR=$UNWOMEN_config_dir
    if ! az account show &>/dev/null
    then
      az login --tenant $UNWOMEN_tenant &>> /tmp/azbastion_$USER.log
      az account set --subscription 'UNWOMEN - Production'
    fi;;
esac

################## IIIM MENU ##################
if [[ $tenant == 1 ]] ; then
  bastion="iiim-conn-dw-bastion"
  rg="RG-IIIM-ConnHub-Datawalk"
  resourceid_prod="/subscriptions/5a0a94a6-32a6-4e5e-a2b7-00b01946c7e6/resourceGroups/RG-IIIM-DATAWALK-PROD/providers/Microsoft.Compute/virtualMachines"
  resourceid_test="/subscriptions/12fb1781-bbd5-463d-8f73-ba1751070a00/resourceGroups/RG-IIIM-DATAWALK-TEST/providers/Microsoft.Compute/virtualMachines"

  environment="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Environment:" 0 0 5 \
    1 "Production" \
    2 "Test")"

  if [[ $environment == 1 ]] ; then
  
    server="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Server:" 0 0 10 \
      1 "iiim-dw-p-appsrv-01" \
      2 "iiim-dw-p-appsrv-02" \
      3 "iiim-dw-p-intsrv-01" \
      4 "iiim-dw-p-intsrv-02" \
      5 "iiim-dw-p-compsrv-01" \
      6 "iiim-dw-p-compsrv-02" \
      7 "iiim-dw-p-compsrv-03" \
      8 "iiim-dw-p-monsrv-01")"

    case $server in
      1)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/iiim-dw-p-appsrv-01 --resource-port 22 --port 9001 ;;
      2)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/iiim-dw-p-appsrv-02 --resource-port 22 --port 9002 ;;
      3)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/iiim-dw-p-intsrv-01 --resource-port 22 --port 9003 ;;
      4)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/iiim-dw-p-intsrv-02 --resource-port 22 --port 9004 ;;
      5)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/iiim-dw-p-compsrv-01 --resource-port 22 --port 9005 ;;
      6)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/iiim-dw-p-compsrv-02 --resource-port 22 --port 9006 ;;
      7)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/iiim-dw-p-compsrv-03 --resource-port 22 --port 9007 ;;
      8)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/iiim-dw-p-monsrv-01 --resource-port 22 --port 9008 ;;
    esac
  fi

  if [[ $environment == 2 ]] ; then

   server="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Server:" 0 0 10 \
     1 "iiim-dw-t-appsrv-01" \
     2 "iiim-dw-t-appsrv-02" \
     3 "iiim-dw-t-intsrv-01" \
     4 "iiim-dw-t-intsrv-02" \
     5 "iiim-dw-t-compsrv-01" \
     6 "iiim-dw-t-compsrv-02" \
     7 "iiim-dw-t-compsrv-03")"

    case $server in
      1)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_test/iiim-dw-t-appsrv-01 --resource-port 22 --port 9009 ;;
      2)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_test/iiim-dw-t-appsrv-02 --resource-port 22 --port 9010 ;;
      3)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_test/iiim-dw-t-intsrv-01 --resource-port 22 --port 9011 ;;
      4)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_test/iiim-dw-t-intsrv-02 --resource-port 22 --port 9012 ;;
      5)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_test/iiim-dw-t-compsrv-01 --resource-port 22 --port 9013 ;;
      6)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_test/iiim-dw-t-compsrv-02 --resource-port 22 --port 9014 ;;
      7)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_test/iiim-dw-t-compsrv-03 --resource-port 22 --port 9015 ;;
    esac
  fi
fi
###############################################

################## IIMM MENU ##################
if [[ $tenant == 2 ]] ; then
  bastion="iimm-conn-dw-bastion"
  rg="RG-IIMM-ConnHub-Datawalk"
  resourceid_prod="/subscriptions/86dd7a2c-aa7c-4fb2-a3c4-4bdbecf7d9cf/resourceGroups/RG-IIMM-DATAWALK-PROD/providers/Microsoft.Compute/virtualMachines"
  resourceid_test="/subscriptions/22ac1dc2-5e93-444c-9b45-80da2ea18872/resourceGroups/RG-IIMM-DATAWALK-TEST/providers/Microsoft.Compute/virtualMachines"

  environment="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Environment:" 0 0 5 \
    1 "Production" \
    2 "Test")"

  if [[ $environment == 1 ]] ; then
  
    server="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Server:" 0 0 10 \
      1 "iimm-dw-p-appsrv-01" \
      2 "iimm-dw-p-appsrv-02" \
      3 "iimm-dw-p-intsrv-01" \
      4 "iimm-dw-p-intsrv-02" \
      5 "iimm-dw-p-compsrv-01" \
      6 "iimm-dw-p-compsrv-02" \
      7 "iimm-dw-p-compsrv-03" \
      8 "iimm-dw-p-monsrv-01")"

    case $server in
      1)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/iimm-dw-p-appsrv-01 --resource-port 22 --port 9016 ;;
      2)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/iimm-dw-p-appsrv-02 --resource-port 22 --port 9017 ;;
      3)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/iimm-dw-p-intsrv-01 --resource-port 22 --port 9018 ;;
      4)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/iimm-dw-p-intsrv-02 --resource-port 22 --port 9019 ;;
      5)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/iimm-dw-p-compsrv-01 --resource-port 22 --port 9020 ;;
      6)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/iimm-dw-p-compsrv-02 --resource-port 22 --port 9021 ;;
      7)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/iimm-dw-p-compsrv-03 --resource-port 22 --port 9022 ;;
      8)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/iimm-dw-p-monsrv-01 --resource-port 22 --port 9023 ;;
    esac
  fi

  if [[ $environment == 2 ]] ; then

   server="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Server:" 0 0 10 \
     1 "iimm-dw-t-appsrv-01" \
     2 "iimm-dw-t-appsrv-02" \
     3 "iimm-dw-t-intsrv-01" \
     4 "iimm-dw-t-intsrv-02" \
     5 "iimm-dw-t-compsrv-01" \
     6 "iimm-dw-t-compsrv-02" \
     7 "iimm-dw-t-compsrv-03")"

    case $server in
      1)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_test/iimm-dw-t-appsrv-01 --resource-port 22 --port 9024 ;;
      2)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_test/iimm-dw-t-appsrv-02 --resource-port 22 --port 9025 ;;
      3)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_test/iimm-dw-t-intsrv-01 --resource-port 22 --port 9026 ;;
      4)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_test/iimm-dw-t-intsrv-02 --resource-port 22 --port 9027 ;;
      5)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_test/iimm-dw-t-compsrv-01 --resource-port 22 --port 9028 ;;
      6)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_test/iimm-dw-t-compsrv-02 --resource-port 22 --port 9029 ;;
      7)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_test/iimm-dw-t-compsrv-03 --resource-port 22 --port 9030 ;;
    esac
  fi
fi
###############################################


################## UNDP MENU ##################
if [[ $tenant == 3 ]] ; then
  bastion="UNDP-PRD-AZRWEU-BASTION-VNET-01"
  rg="UNDP-PRD-AZRWEU-HUB"
  resourceid_prod="/subscriptions/e9d86b44-b795-49db-a164-52dd079ea32e/resourceGroups/UNDP-AZRWEU-LEGACY-PRODUCTION/providers/Microsoft.Compute/virtualMachines"
  resourceid_test="/subscriptions/e9d86b44-b795-49db-a164-52dd079ea32e/resourceGroups/UNDP-AZRWEU-LEGACY-NONPRODUCTION/providers/Microsoft.Compute/virtualMachines"

  environment="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Environment:" 0 0 5 \
    1 "Production" \
    2 "Test")"

  if [[ $environment == 1 ]] ; then

    server="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Server:" 0 0 10 \
      1 "DPLPRODCF02" \
      2 "DPSPRODCF02" \
      3 "DPWEBFS02" \
      4 "DPLPRODCFSM02")"

    case $server in
      1)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/DPLPRODCF02 --resource-port 22 --port 9031 ;;
      2)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/DPSPRODCF02 --resource-port 22 --port 9032 ;;
      3)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/DPWEBFS02 --resource-port 22 --port 9033 ;;
      4)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_prod/DPLPRODCFSM02 --resource-port 22 --port 9034 ;;
    esac
  fi

  if [[ $environment == 2 ]] ; then

   server="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Server:" 0 0 10 \
     1 "DPLNONPRODCF02")"

    case $server in
      1)
         az network bastion tunnel --name $bastion --resource-group $rg --target-resource-id $resourceid_test/DPLNONPRODCF02 --resource-port 22 --port 9035 ;;
    esac
  fi
fi
###############################################
