#!/bin/bash
#
# Open a tunnel with a server through Azure Bastion
# https://github.com/luisbunuel/aztools

# LIST OF AZURE TENANTS
IIIM_tenant="iiimprod.onmicrosoft.com"
IIIM_config_dir="$HOME/.azure_IIIM"
IIMM_tenant="mymeprod.onmicrosoft.com"
IIMM_config_dir="$HOME/.azure_IIMM"
UNDP_tenant="iccundp.onmicrosoft.com"
UNDP_config_dir="$HOME/.azure_UNDP"
UNDPBIO_tenant="iccundp.onmicrosoft.com"
UNDPBIO_config_dir="$HOME/.azure_UNDPBIO"
UNWOMEN_tenant="unwomen.onmicrosoft.com"
UNWOMEN_config_dir="$HOME/.azure_WOMEN"

export AZURE_CONFIG_DIR=$IIIM_config_dir
if az account get-access-token &>/dev/null; then
   iiim="\Zu\Z1IIIM"
else
   iiim="IIIM"
fi

export AZURE_CONFIG_DIR=$IIMM_config_dir
if az account get-access-token &>/dev/null; then
   iimm="\Zu\Z1IIMM"
else
   iimm="IIMM"
fi

export AZURE_CONFIG_DIR=$UNDP_config_dir
if az account get-access-token &>/dev/null; then
   undp="\Zu\Z1UNDP"
else
   undp="UNDP"
fi

export AZURE_CONFIG_DIR=$UNDPBIO_config_dir
if az account get-access-token &>/dev/null; then
   undpbio="\Zu\Z1UNDPBIO"
else
   undpbio="UNDPBIO"
fi

export AZURE_CONFIG_DIR=$UNWOMEN_config_dir
if az account get-access-token &>/dev/null; then
   unwomen="\Zu\Z1UNWOMEN"
else
   unwomen="UNWOMEN"
fi

tenant="$(dialog --colors --backtitle "Azure Bastion tunnel connection" --title "\Zb\Z0AZBASTION" --stdout --default-item 1 --menu "Select Tenant" 0 0 6 \
  1 "$iiim" \
  2 "$iimm" \
  3 "$undp" \
  4 "$unwomen" \
  5 "$undpbio" )"

case $tenant in
  1)
    export AZURE_CONFIG_DIR=$IIIM_config_dir
   az config set extension.use_dynamic_install=yes_without_prompt &>/dev/null
    if ! az account get-access-token &>/dev/null; then
      az login --tenant $IIIM_tenant &>> /tmp/azbastion_$USER.log
    fi
    az account set --subscription 'IIIM - Connectivity Hub';;
  2)
    export AZURE_CONFIG_DIR=$IIMM_config_dir
   az config set extension.use_dynamic_install=yes_without_prompt &>/dev/null
    if ! az account get-access-token &>/dev/null; then
      az login --tenant $IIMM_tenant &>> /tmp/azbastion_$USER.log
    fi
    az account set --subscription 'IIMM - Connectivity Hub' ;;
  3)
    export AZURE_CONFIG_DIR=$UNDP_config_dir
   az config set extension.use_dynamic_install=yes_without_prompt &>/dev/null
    if ! az account get-access-token &>/dev/null; then
      az login --tenant $UNDP_tenant &>> /tmp/azbastion_$USER.log
    fi
    az account set --subscription 'ICCUNDP - Production';;
  4) 
    export AZURE_CONFIG_DIR=$UNWOMEN_config_dir
   az config set extension.use_dynamic_install=yes_without_prompt &>/dev/null
    if ! az account get-access-token &>/dev/null; then
      az login --tenant $UNWOMEN_tenant &>> /tmp/azbastion_$USER.log  
    fi
    az account set --subscription 'UNWOMEN - Production';;
  5)
    export AZURE_CONFIG_DIR=$UNDPBIO_config_dir
        az config set extension.use_dynamic_install=yes_without_prompt &>/dev/null
    if ! az account get-access-token &>/dev/null; then
      az login --tenant $UNDPBIO_tenant &>> /tmp/azbastion_$USER.log
    fi
    az account set --subscription 'UNDP - UN Biodiversity Lab Hosting - ELSA';;

esac

################## IIIM MENU ##################
if [[ $tenant == 1 ]] ; then
  bastion="iiim-conn-dw-bastion"
  rg="RG-IIIM-ConnHub-Datawalk"
  resourceid_prod="/subscriptions/5a0a94a6-32a6-4e5e-a2b7-00b01946c7e6/resourceGroups/RG-IIIM-DATAWALK-PROD/providers/Microsoft.Compute/virtualMachines"
  resourceid_test="/subscriptions/12fb1781-bbd5-463d-8f73-ba1751070a00/resourceGroups/RG-IIIM-DATAWALK-TEST/providers/Microsoft.Compute/virtualMachines"

  environment="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Environment:" 0 0 5 \
    1 "Production" \
    2 "Test")"

  if [[ $environment == 1 ]] ; then
  
    server="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Server:" 0 0 10 \
      1 "iiim-dw-p-appsrv-01" \
      2 "iiim-dw-p-appsrv-02" \
      3 "iiim-dw-p-intsrv-01" \
      4 "iiim-dw-p-intsrv-02" \
      5 "iiim-dw-p-compsrv-01" \
      6 "iiim-dw-p-compsrv-02" \
      7 "iiim-dw-p-compsrv-03" \
      8 "iiim-dw-p-monsrv-01")"

    case $server in
      1)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.62.4 --resource-port 22 --port 9001 ;;
      2)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.62.5 --resource-port 22 --port 9002 ;;
      3)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.62.36 --resource-port 22 --port 9003 ;;
      4)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.62.37 --resource-port 22 --port 9004 ;;
      5)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.62.68 --resource-port 22 --port 9005 ;;
      6)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.62.69 --resource-port 22 --port 9006 ;;
      7)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.62.70 --resource-port 22 --port 9007 ;;
      8)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.62.38 --resource-port 22 --port 9008 ;;
    esac
  fi

  if [[ $environment == 2 ]] ; then

   server="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Server:" 0 0 10 \
     1 "iiim-dw-t-appsrv-01" \
     2 "iiim-dw-t-appsrv-02" \
     3 "iiim-dw-t-intsrv-01" \
     4 "iiim-dw-t-intsrv-02" \
     5 "iiim-dw-t-compsrv-01" \
     6 "iiim-dw-t-compsrv-02" \
     7 "iiim-dw-t-compsrv-03")"

    case $server in
      1)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.61.4 --resource-port 22 --port 9009 ;;
      2)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.61.5 --resource-port 22 --port 9010 ;;
      3)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.61.36 --resource-port 22 --port 9011 ;;
      4)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.61.37 --resource-port 22 --port 9012 ;;
      5)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.61.68 --resource-port 22 --port 9013 ;;
      6)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.61.69 --resource-port 22 --port 9014 ;;
      7)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.61.70 --resource-port 22 --port 9015 ;;
    esac
  fi
fi
###############################################

################## IIMM MENU ##################
if [[ $tenant == 2 ]] ; then
  bastion="iimm-conn-dw-bastion"
  rg="RG-IIMM-ConnHub-Datawalk"

  environment="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Environment:" 0 0 5 \
    1 "Production" \
    2 "Test")"

  if [[ $environment == 1 ]] ; then
  
    server="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Server:" 0 0 10 \
      1 "iimm-dw-p-appsrv-01" \
      2 "iimm-dw-p-appsrv-02" \
      3 "iimm-dw-p-intsrv-01" \
      4 "iimm-dw-p-intsrv-02" \
      5 "iimm-dw-p-compsrv-01" \
      6 "iimm-dw-p-compsrv-02" \
      7 "iimm-dw-p-compsrv-03" \
      8 "iimm-dw-p-monsrv-01")"

    case $server in
      1)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.65.4 --resource-port 22 --port 9016 ;;
      2)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.65.5 --resource-port 22 --port 9017 ;;
      3)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.65.36 --resource-port 22 --port 9018 ;;
      4)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.65.37 --resource-port 22 --port 9019 ;;
      5)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.65.68 --resource-port 22 --port 9020 ;;
      6)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.65.69 --resource-port 22 --port 9021 ;;
      7)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.65.70 --resource-port 22 --port 9022 ;;
      8)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.65.38 --resource-port 22 --port 9023 ;;
    esac
  fi

  if [[ $environment == 2 ]] ; then

   server="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Server:" 0 0 10 \
     1 "iimm-dw-t-appsrv-01" \
     2 "iimm-dw-t-appsrv-02" \
     3 "iimm-dw-t-intsrv-01" \
     4 "iimm-dw-t-intsrv-02" \
     5 "iimm-dw-t-compsrv-01" \
     6 "iimm-dw-t-compsrv-02" \
     7 "iimm-dw-t-compsrv-03")"

    case $server in
      1)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.64.4 --resource-port 22 --port 9024 ;;
      2)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.64.5 --resource-port 22 --port 9025 ;;
      3)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.64.36 --resource-port 22 --port 9026 ;;
      4)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.64.37 --resource-port 22 --port 9027 ;;
      5)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.64.69 --resource-port 22 --port 9028 ;;
      6)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.64.70 --resource-port 22 --port 9029 ;;
      7)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.64.71 --resource-port 22 --port 9030 ;;
    esac
  fi
fi
###############################################

################## UNDP MENU ##################
if [[ $tenant == 3 ]] ; then
  bastion="UNDP-PRD-AZRWEU-BASTION-VNET-01"
  rg="UNDP-PRD-AZRWEU-HUB"

  environment="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Environment:" 0 0 5 \
    1 "Production" \
    2 "Test")"

  if [[ $environment == 1 ]] ; then

    server="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Server:" 0 0 10 \
      1 "DPLPRODCF02" \
      2 "DPSPRODCF02")"

    case $server in
      1)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.1.46 --resource-port 22 --port 9031 ;;
      2)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.1.47 --resource-port 22 --port 9032 ;;
    esac
  fi

  if [[ $environment == 2 ]] ; then

   server="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Server:" 0 0 10 \
     1 "DPLNONPRODCF02")"

    case $server in
      1)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address 10.88.1.42 --resource-port 22 --port 9035 ;;
    esac
  fi
fi
###############################################

################## UNDP BIO ##################
if [[ $tenant == 5 ]] ; then
  bastion="undp-elsa-bastion"
  rg="RG-undp-elsa-prod"

  environment="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Environment:" 0 0 5 \
    1 "Production")"

  if [[ $environment == 1 ]] ; then

    server="$(dialog --backtitle "Azure Bastion tunnel connection" --stdout --default-item 1 --menu "Select Server:" 0 0 10 \
      1 "undpbio")"

    case $server in
      1)
         az network bastion tunnel --name $bastion --resource-group $rg --target-ip-address  10.88.2.68  --resource-port 22 --port 9036 ;;
    esac
  fi
fi
###############################################
